In [1]:
import numpy as np
import pandas as pd

from pandas import Series, DataFrame

# Merge

In [2]:
dframe1 = DataFrame({'key':['X','Z','Y','Z','X','X'],'data_set_1':np.arange(6)})
dframe1

key  data_set_1
0   X           0
1   Z           1
2   Y           2
3   Z           3
4   X           4
5   X           5

In [3]:
dframe2 = DataFrame({'key':['Q','Y','Z'],'data_set_2':[1,2,3]})
dframe2

key  data_set_2
0   Q           1
1   Y           2
2   Z           3

In [4]:
pd.merge(dframe1,dframe2)

key  data_set_1  data_set_2
0   Z           1           3
1   Z           3           3
2   Y           2           2

In [5]:
pd.merge(dframe1,dframe2,on='key')

key  data_set_1  data_set_2
0   Z           1           3
1   Z           3           3
2   Y           2           2

In [6]:
pd.merge(dframe1,dframe2,on='key',how='left')

key  data_set_1  data_set_2
0   X           0         NaN
1   Z           1         3.0
2   Y           2         2.0
3   Z           3         3.0
4   X           4         NaN
5   X           5         NaN

In [7]:
pd.merge(dframe1,dframe2,on='key',how='right')

key  data_set_1  data_set_2
0   Z         1.0           3
1   Z         3.0           3
2   Y         2.0           2
3   Q         NaN           1

In [8]:
pd.merge(dframe1,dframe2,on='key',how='outer')

key  data_set_1  data_set_2
0   X         0.0         NaN
1   X         4.0         NaN
2   X         5.0         NaN
3   Z         1.0         3.0
4   Z         3.0         3.0
5   Y         2.0         2.0
6   Q         NaN         1.0

In [9]:
dframe3 = DataFrame({'key':['X','X','X','Y','Z','Z'],'data_set_3':range(6)})

In [10]:
dframe4 = DataFrame({'key':['Y','Y','X','X','Z'],'data_set_4':range(5)})

In [11]:
dframe3

key  data_set_3
0   X           0
1   X           1
2   X           2
3   Y           3
4   Z           4
5   Z           5

In [12]:
dframe4

key  data_set_4
0   Y           0
1   Y           1
2   X           2
3   X           3
4   Z           4

In [13]:
pd.merge(dframe3,dframe4)

key  data_set_3  data_set_4
0   X           0           2
1   X           0           3
2   X           1           2
3   X           1           3
4   X           2           2
5   X           2           3
6   Y           3           0
7   Y           3           1
8   Z           4           4
9   Z           5           4

In [14]:
df_left = DataFrame({'key1':['SF','SF','LA',],
                     'key2':['one','two','one'],
                     'left_data':[10,20,30]})

In [15]:
df_right = DataFrame({'key1':['SF','SF','LA','LA'],
                     'key2':['one','one','one','two'],
                     'left_data':[40,50,60,70]})

In [16]:
df_left

key1 key2  left_data
0   SF  one         10
1   SF  two         20
2   LA  one         30

In [17]:
df_right

key1 key2  left_data
0   SF  one         40
1   SF  one         50
2   LA  one         60
3   LA  two         70

In [18]:
pd.merge(df_left,df_right,on=['key1','key2'],how='outer')

key1 key2  left_data_x  left_data_y
0   SF  one         10.0         40.0
1   SF  one         10.0         50.0
2   SF  two         20.0          NaN
3   LA  one         30.0         60.0
4   LA  two          NaN         70.0

In [19]:
pd.merge(df_left,df_right,on='key1')

key1 key2_x  left_data_x key2_y  left_data_y
0   SF    one           10    one           40
1   SF    one           10    one           50
2   SF    two           20    one           40
3   SF    two           20    one           50
4   LA    one           30    one           60
5   LA    one           30    two           70

In [20]:
pd.merge(df_left,df_right,on='key1',suffixes=('_lefty','_righty'))

key1 key2_lefty  left_data_lefty key2_righty  left_data_righty
0   SF        one               10         one                40
1   SF        one               10         one                50
2   SF        two               20         one                40
3   SF        two               20         one                50
4   LA        one               30         one                60
5   LA        one               30         two                70

# Merge on index

In [21]:
df_left = DataFrame({'key':['X','Y','Z','X','Y'],
                     'data':range(5)})
df_left

key  data
0   X     0
1   Y     1
2   Z     2
3   X     3
4   Y     4

In [22]:
df_right= DataFrame({'group_data':[10,20]},index=['X','Y'])
df_right

group_data
X          10
Y          20

In [23]:
# Merge left by key and right by index
pd.merge(df_left,df_right,left_on='key',right_index=True)

key  data  group_data
0   X     0          10
3   X     3          10
1   Y     1          20
4   Y     4          20

In [24]:
df_left_hr = DataFrame({'key1':['SF','SF','SF','LA','LA'],
                     'key2':[10,20,30,20,30],
                     'data_set':np.arange(5.)})
df_left_hr

key1  key2  data_set
0   SF    10       0.0
1   SF    20       1.0
2   SF    30       2.0
3   LA    20       3.0
4   LA    30       4.0

In [25]:
df_right_hr = DataFrame(np.arange(10).reshape(5,2),
                       index=[['LA','LA','SF','SF','SF'],
                             [20,10,10,10,20]],
                       columns=['col_1','col_2'])
df_right_hr

col_1  col_2
LA 20      0      1
   10      2      3
SF 10      4      5
   10      6      7
   20      8      9

In [26]:
# Merge left by key and right by index
pd.merge(df_left_hr,df_right_hr,left_on=['key1','key2'],right_index=True)

key1  key2  data_set  col_1  col_2
0   SF    10       0.0      4      5
0   SF    10       0.0      6      7
1   SF    20       1.0      8      9
3   LA    20       3.0      0      1

In [27]:
df_left

key  data
0   X     0
1   Y     1
2   Z     2
3   X     3
4   Y     4

In [28]:
df = DataFrame({'key':['X','X'],'data':[4,6]})

In [29]:
df_left.join(df,lsuffix='z')

keyz  dataz  key  data
0    X      0    X   4.0
1    Y      1    X   6.0
2    Z      2  NaN   NaN
3    X      3  NaN   NaN
4    Y      4  NaN   NaN

In [30]:
df_left.join(df_right)

key  data  group_data
0   X     0         NaN
1   Y     1         NaN
2   Z     2         NaN
3   X     3         NaN
4   Y     4         NaN

# Concatenate

In [31]:
arr1 = np.arange(9).reshape((3,3))

arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [33]:
ser1 = Series([0,1,2],index=['T','U','V'])

ser2 = Series([3,4],index=['X','Y'])

In [34]:
ser1

T    0
U    1
V    2
dtype: int64

In [35]:
ser2

X    3
Y    4
dtype: int64

In [36]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [37]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [38]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [39]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])

dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [40]:
dframe1

X         Y         Z
0  0.579172  0.439758  0.557274
1  0.575471  1.091601  0.252262
2  0.753184 -0.646354 -0.259920
3  1.736829 -2.484094  1.561073

In [41]:
dframe2

Y         Q         X
0  0.402830 -1.541039 -0.223138
1  0.310104  0.233134 -1.117100
2  0.731987 -1.325079 -0.712310

In [42]:
pd.concat([dframe1,dframe2])

X         Y         Z         Q
0  0.579172  0.439758  0.557274       NaN
1  0.575471  1.091601  0.252262       NaN
2  0.753184 -0.646354 -0.259920       NaN
3  1.736829 -2.484094  1.561073       NaN
0 -0.223138  0.402830       NaN -1.541039
1 -1.117100  0.310104       NaN  0.233134
2 -0.712310  0.731987       NaN -1.325079

In [43]:
pd.concat([dframe1,dframe1])

X         Y         Z
0  0.579172  0.439758  0.557274
1  0.575471  1.091601  0.252262
2  0.753184 -0.646354 -0.259920
3  1.736829 -2.484094  1.561073
0  0.579172  0.439758  0.557274
1  0.575471  1.091601  0.252262
2  0.753184 -0.646354 -0.259920
3  1.736829 -2.484094  1.561073

In [44]:
pd.concat([dframe1,dframe1],ignore_index=True)

X         Y         Z
0  0.579172  0.439758  0.557274
1  0.575471  1.091601  0.252262
2  0.753184 -0.646354 -0.259920
3  1.736829 -2.484094  1.561073
4  0.579172  0.439758  0.557274
5  0.575471  1.091601  0.252262
6  0.753184 -0.646354 -0.259920
7  1.736829 -2.484094  1.561073

# Combining DataFrame

In [45]:
ser1 = Series([2,np.nan,4,np.nan,6,np.nan],
             index=['Q','R','S','T','U','V'])

ser1

Q    2.0
R    NaN
S    4.0
T    NaN
U    6.0
V    NaN
dtype: float64

In [46]:
ser2 = Series(np.arange(len(ser1)),dtype=np.float64,
             index=['Q','R','S','T','U','V'])

ser2

Q    0.0
R    1.0
S    2.0
T    3.0
U    4.0
V    5.0
dtype: float64

In [47]:
Series(np.where(pd.isnull(ser1),ser2,ser1),index=ser1.index) # Chỗ nào ser1 null thì bỏ gtri ser2 vào

Q    2.0
R    1.0
S    4.0
T    3.0
U    6.0
V    5.0
dtype: float64

In [48]:
ser1.combine_first(ser2)

Q    2.0
R    1.0
S    4.0
T    3.0
U    6.0
V    5.0
dtype: float64

In [49]:
nan = np.nan
dframe_odd = DataFrame({'X':[1.,np.nan,3.,np.nan],
                       'Y':[np.nan,5.,np.nan,7.0],
                       'Z':[np.nan,9.,np.nan,11.]})

In [50]:
dframe_even = DataFrame({'X':[1.,4.,nan,6.,8.],
                       'Y':[nan,10.,12.,14.,16.]})

In [51]:
dframe_odd

X    Y     Z
0  1.0  NaN   NaN
1  NaN  5.0   9.0
2  3.0  NaN   NaN
3  NaN  7.0  11.0

In [52]:
dframe_even

X     Y
0  1.0   NaN
1  4.0  10.0
2  NaN  12.0
3  6.0  14.0
4  8.0  16.0

In [53]:
dframe_odd.combine_first(dframe_even)

X     Y     Z
0  1.0   NaN   NaN
1  4.0   5.0   9.0
2  3.0  12.0   NaN
3  6.0   7.0  11.0
4  8.0  16.0   NaN

# Reshaping

In [54]:
df1=DataFrame(np.arange(8).reshape(2,4), 
              index=pd.Index(['LA','SF'],name='city'),
             columns=pd.Index(['A','B','C','D'],name='letter'))
df1

letter  A  B  C  D
city              
LA      0  1  2  3
SF      4  5  6  7

In [55]:
df_st = df1.stack()

In [56]:
df_st

city  letter
LA    A         0
      B         1
      C         2
      D         3
SF    A         4
      B         5
      C         6
      D         7
dtype: int64

In [57]:
df_st.unstack()

letter  A  B  C  D
city              
LA      0  1  2  3
SF      4  5  6  7

In [58]:
df_st.unstack('city')

city    LA  SF
letter        
A        0   4
B        1   5
C        2   6
D        3   7

In [59]:
ser1=Series([0,1,2],index=['q','x','y'])
ser2=Series([4,5,6],index=['x','y','z'])

In [60]:
df = pd.concat([ser1,ser2],keys=['Alpha','Beta'])
df

Alpha  q    0
       x    1
       y    2
Beta   x    4
       y    5
       z    6
dtype: int64

In [61]:
df.unstack()

q    x    y    z
Alpha  0.0  1.0  2.0  NaN
Beta   NaN  4.0  5.0  6.0

In [62]:
df=df.unstack()

In [63]:
df.stack(dropna=False)

Alpha  q    0.0
       x    1.0
       y    2.0
       z    NaN
Beta   q    NaN
       x    4.0
       y    5.0
       z    6.0
dtype: float64

# Pivoting

In [64]:
# What information you actuallly want to know?

In [65]:
import pandas.util.testing as tm; tm.N = 3

#Create an unpivoted func
def unpivot(frame):
    N, K =frame.shape
    
    data = {'value':frame.values.ravel('F'),
           'variable':np.asarray(frame.columns).repeat(N),
           'date':np.tile(np.asarray(frame.index),K)}
    #Return a dataframe
    return DataFrame(data,columns=['date','variable','value'])
dframe = unpivot(tm.makeTimeDataFrame())
dframe

/home/vinhngo/miniconda3/envs/sp/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  """Entry point for launching an IPython kernel.


date variable     value
0   2000-01-03        A -0.099824
1   2000-01-04        A  1.148755
2   2000-01-05        A  0.547155
3   2000-01-06        A -1.988492
4   2000-01-07        A  1.360192
..         ...      ...       ...
115 2000-02-07        D  0.395652
116 2000-02-08        D -0.287659
117 2000-02-09        D -0.853909
118 2000-02-10        D -1.176341
119 2000-02-11        D  0.481576

[120 rows x 3 columns]

In [66]:
dframe_piv = dframe.pivot('date','variable','value') 

In [67]:
dframe_piv

variable           A         B         C         D
date                                              
2000-01-03 -0.099824 -0.568852 -0.508182 -1.631128
2000-01-04  1.148755  1.941144  0.608953  1.995248
2000-01-05  0.547155 -1.399208  0.042782 -0.510939
2000-01-06 -1.988492 -0.701611  0.158033 -0.002006
2000-01-07  1.360192  0.316366  1.626941 -0.925298
2000-01-10 -0.254229 -0.325085 -0.486324  1.015715
2000-01-11  0.403400 -0.598568  0.161233  0.294389
2000-01-12  1.636558 -0.420236  0.041613 -0.723017
2000-01-13 -1.428902 -0.301988 -0.195011  0.118868
2000-01-14 -0.058360  0.483001 -1.188931  1.131229
2000-01-17  0.236109 -0.167660  0.993067 -1.226300
2000-01-18 -1.851476 -1.315173 -0.579690 -1.653354
2000-01-19  2.055665 -0.850810  0.456137 -0.060293
2000-01-20  1.128959  1.558579  0.179080  0.237247
2000-01-21 -0.284855  0.470247  1.459119 -0.515180
2000-01-24 -0.403782 -0.379029 -1.369820  0.779748
2000-01-25  0.532673 -0.714915  0.209602  1.176711
2000-01-26 -0.680705  0.584877 -1.460474 -0.219553
2000-01-27 -0.203300  0.264773 -1.469818  0.855299
2000-01-28  1.467752  0.582527 -1.082718 -0.336979
2000-01-31  0.300584  0.932368 -0.664921  0.297007
2000-02-01  1.081448  0.109566  1.157688 -1.242486
2000-02-02 -1.216200  0.804000 -1.758824  0.025082
2000-02-03 -0.908379 -1.305746 -0.765383  0.216801
2000-02-04 -0.651074 -0.383074  0.525184  1.192028
2000-02-07  1.274652 -1.148249  0.149928  0.395652
2000-02-08  2.269916  0.258246 -1.371178 -0.287659
2000-02-09  0.481105  0.052024 -1.203275 -0.853909
2000-02-10  0.228557 -1.160441  0.477218 -1.176341
2000-02-11 -0.893961  0.508901 -0.513053  0.481576

# Duplicate in DataFrame

In [68]:
dframe = DataFrame({'key1':['A']*2 + ['B']*3,
                   'key2':[2,2,2,3,3]})
dframe

key1  key2
0    A     2
1    A     2
2    B     2
3    B     3
4    B     3

In [69]:
dframe.duplicated()

0    False
1     True
2    False
3    False
4     True
dtype: bool

In [70]:
dframe.drop_duplicates()

key1  key2
0    A     2
2    B     2
3    B     3

In [71]:
dframe.drop_duplicates(['key1'])

key1  key2
0    A     2
2    B     2

In [72]:
dframe.drop_duplicates(['key1'],keep='last')

key1  key2
1    A     2
4    B     3

# Mapping

In [73]:
dframe = DataFrame({'city':['Alma','Brian Head','Fox Park'],
                   'altitude':[3158,3000,2762]})
dframe

city  altitude
0        Alma      3158
1  Brian Head      3000
2    Fox Park      2762

In [74]:
state_map = {'Alma':'Colorado','Brian Head':'Utah','Fox Park':'Wyoming'}

In [75]:
dframe['state'] = dframe['city'].map(state_map)
dframe

city  altitude     state
0        Alma      3158  Colorado
1  Brian Head      3000      Utah
2    Fox Park      2762   Wyoming

# Replace

In [76]:
ser1 = Series([1,2,3,4,1,2,3,4])
ser1

0    1
1    2
2    3
3    4
4    1
5    2
6    3
7    4
dtype: int64

In [77]:
ser1.replace(1,np.nan)

0    NaN
1    2.0
2    3.0
3    4.0
4    NaN
5    2.0
6    3.0
7    4.0
dtype: float64

In [78]:
ser1.replace([1,4],[100,400])

0    100
1      2
2      3
3    400
4    100
5      2
6      3
7    400
dtype: int64

In [79]:
ser1.replace({4:np.nan})

0    1.0
1    2.0
2    3.0
3    NaN
4    1.0
5    2.0
6    3.0
7    NaN
dtype: float64

# Rename Index

In [80]:
dframe = DataFrame(np.arange(12).reshape(3,4),index=['NY','LA','SF'],
                  columns=['A','B','C','D'])
dframe

A  B   C   D
NY  0  1   2   3
LA  4  5   6   7
SF  8  9  10  11

In [81]:
dframe.index.map(str.lower)

Index(['ny', 'la', 'sf'], dtype='object')

In [82]:
dframe.index = dframe.index.map(str.lower)
dframe

A  B   C   D
ny  0  1   2   3
la  4  5   6   7
sf  8  9  10  11

In [83]:
dframe.rename(index=str.title,columns=str.lower)

a  b   c   d
Ny  0  1   2   3
La  4  5   6   7
Sf  8  9  10  11

In [84]:
dframe.rename(index={'ny':'New York'},columns={'A':'Alpha'})

Alpha  B   C   D
New York      0  1   2   3
la            4  5   6   7
sf            8  9  10  11

In [85]:
dframe

A  B   C   D
ny  0  1   2   3
la  4  5   6   7
sf  8  9  10  11

In [86]:
dframe.rename(index={'ny':'New York'},inplace=True)
dframe

A  B   C   D
New York  0  1   2   3
la        4  5   6   7
sf        8  9  10  11

# Binning

In [87]:
years = [1990,1991,1992,2008,2012,2015,1987,1969,2013,2008,1999]
decade_bins = [1960,1970,1980,1990,2000,2010,2020]
decade_cat = pd.cut(years,decade_bins)
decade_cat

[(1980, 1990], (1990, 2000], (1990, 2000], (2000, 2010], (2010, 2020], ..., (1980, 1990], (1960, 1970], (2010, 2020], (2000, 2010], (1990, 2000]]
Length: 11
Categories (6, interval[int64]): [(1960, 1970] < (1970, 1980] < (1980, 1990] < (1990, 2000] < (2000, 2010] < (2010, 2020]]

In [88]:
decade_cat.categories

IntervalIndex([(1960, 1970], (1970, 1980], (1980, 1990], (1990, 2000], (2000, 2010], (2010, 2020]],
              closed='right',
              dtype='interval[int64]')

In [89]:
pd.value_counts(decade_cat)

(2010, 2020]    3
(1990, 2000]    3
(2000, 2010]    2
(1980, 1990]    2
(1960, 1970]    1
(1970, 1980]    0
dtype: int64

In [90]:
pd.cut(years,2,precision=1)

[(1969.0, 1992.0], (1969.0, 1992.0], (1969.0, 1992.0], (1992.0, 2015.0], (1992.0, 2015.0], ..., (1969.0, 1992.0], (1969.0, 1992.0], (1992.0, 2015.0], (1992.0, 2015.0], (1992.0, 2015.0]]
Length: 11
Categories (2, interval[float64]): [(1969.0, 1992.0] < (1992.0, 2015.0]]

# Outliers

In [91]:
np.random.seed(12345)

In [92]:
df = DataFrame(np.random.randn(1000,4))

In [93]:
df.head()

0         1         2         3
0 -0.204708  0.478943 -0.519439 -0.555730
1  1.965781  1.393406  0.092908  0.281746
2  0.769023  1.246435  1.007189 -1.296221
3  0.274992  0.228913  1.352917  0.886429
4 -2.001637 -0.371843  1.669025 -0.438570

In [94]:
df.tail()

0         1         2         3
995  1.089085  0.251232 -1.451985  1.653126
996 -0.478509 -0.010663 -1.060881 -1.502870
997 -1.946267  1.013592  0.037333  0.133304
998 -1.293122 -0.322542 -0.782960 -0.303340
999  0.089987  0.292291  1.177706  0.882755

In [95]:
df.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067684     0.067924     0.025598    -0.002298
std       0.998035     0.992106     1.006835     0.996794
min      -3.428254    -3.548824    -3.184377    -3.745356
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.366626     2.653656     3.260383     3.927528

In [96]:
col=df[0]
col.head()

0   -0.204708
1    1.965781
2    0.769023
3    0.274992
4   -2.001637
Name: 0, dtype: float64

In [97]:
col[np.abs(col)>3]

523   -3.428254
900    3.366626
Name: 0, dtype: float64

In [98]:
df[(np.abs(df)>3).any(1)]

0         1         2         3
5   -0.539741  0.476985  3.248944 -1.021228
97  -0.774363  0.552936  0.106061  3.927528
102 -0.655054 -0.565230  3.176873  0.959533
305 -2.315555  0.457246 -0.025907 -3.399312
324  0.050188  1.951312  3.260383  0.963301
400  0.146326  0.508391 -0.196713 -3.745356
499 -0.293333 -0.242459 -3.056990  1.918403
523 -3.428254 -0.296336 -0.439938 -0.867165
586  0.275144  1.179227 -3.184377  1.369891
808 -0.362528 -3.548824  1.553205 -2.186301
900  3.366626 -2.372214  0.851010  1.332846

In [99]:
df[np.abs(df)>3] = np.sign(df)*3

In [100]:
df.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.067623     0.068473     0.025153    -0.002081
std       0.995485     0.990253     1.003977     0.989736
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.774890    -0.591841    -0.641675    -0.644144
50%      -0.116401     0.101143     0.002073    -0.013611
75%       0.616366     0.780282     0.680391     0.654328
max       3.000000     2.653656     3.000000     3.000000

# Permutation

### Randomly reorder series or rows in DF 

In [101]:
df = DataFrame(np.arange(16).reshape(4,4))

In [102]:
blender = np.random.permutation(4)
blender

array([1, 3, 2, 0])

In [103]:
df

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [104]:
df.take(blender)

0   1   2   3
1   4   5   6   7
3  12  13  14  15
2   8   9  10  11
0   0   1   2   3

In [105]:
box = np.array([1,2,3])

In [106]:
shaker = np.random.randint(0,len(box),size=10)
shaker

array([2, 0, 2, 0, 2, 0, 2, 0, 2, 2])

In [107]:
hand_grabs = box.take(shaker)
hand_grabs

array([3, 1, 3, 1, 3, 1, 3, 1, 3, 3])